pub mod animated_sprite;
pub mod autoremove;
pub mod check_bullet_collisions;
pub mod game_setup;
pub mod keyboard_directions;
pub mod linear_movement;
pub mod linear_movement_within_game_bounds;
pub mod position_seeker;
pub mod shooter;
