[package]
name = "game_core"
version = "0.1.0"
edition = "2021"

[dependencies]
common_macros = "0.1.1"
lazy_static = "1.5.0"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.127"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]
